### ISSUE TITLE
differenece between “        _app.postgres_pool = await asyncpg.create_pool(”  and  “engine = create_async_engine(”

### ISSUE THREAD

**Issue by sanwei111** [grillazz/fastapi-sqlalchemy-asyncpg#183]
in main.py,  you make a pool
while in database,py you make a connection

i wonder the difference?
i can see you will use the "connection" in get_db for cursor, but how about the "pool"?

**Comment by grillazz** [comment]
@sanwei111 main reason is showcase as option. 
`_app.postgres_pool = await asyncpg.create_pool` is kinda long live conn to database with limited number of connection btw min and max. You can send few DDLs or DML at same time and it is definitely faster than `engine = create_async_engine(` which is standard approach. Also on pool you need to have prepared SQLs - take a look here https://github.com/grillazz/fastapi-sqlalchemy-asyncpg/blob/main/app/api/stuff.py#L56
Also you can read https://magicstack.github.io/asyncpg/current/api/index.html#connection-pools

**Comment by sanwei111** [comment]
@grillazz excellent，marvellous，remarkable！！！you are so nice, thx for response me!!!!
