### ISSUE TITLE
Unnecessary method

### ISSUE THREAD

**Issue by yorickvanzweeden** [grillazz/fastapi-sqlalchemy-asyncpg#69]
Hey grillazz! Thanks for this awesome repo :)

Does this method have any purpose? It does not seem to be referenced anywhere.
https://github.com/grillazz/fastapi-sqlalchemy-asyncpg/blob/e71d41a8ee60933e169eb0ce188e46fdc7591694/app/database.py#L36-L50

**Comment by grillazz** [comment]
thx @yorickvanzweeden i was juts one of examples - I will drop it in next PR
