### ISSUE TITLE
SQLAlchemy Engine disposal

### ISSUE THREAD

**Issue by hmbui-noze** [grillazz/fastapi-sqlalchemy-asyncpg#98]
I've come across your project and I really appreciate what you've done.
I have a question that bugs me for a long time and I've never seen any project addressing it, including yours.

When you create an `AsyncEngine`, you are supposed to [dispose](https://docs.sqlalchemy.org/en/13/core/connections.html#engine-disposal) it, ideally in `shutdown` event. However, I never see anyone doing it in practice. Is it because you rely on GC of Python to clean it for you?

**Comment by grillazz** [comment]
@hmbui-noze I'm using `dispose()` for AsyncEngine created in function scope to close and clean-up pooled connections - for db session injected with DI it should be fine to not use `dispose()`
